import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="flex justify-between items-center">
        <div>Logo</div>
        <div>
          <ul className="flex">
            <li>
              <a href="">Home</a>
            </li>
            <li>
              <a href="">About</a>
            </li>
            <li className="">
              <a href="">contact</a>
            </li>
          </ul>
        </div>

        <div>
          <button className="bg-black text-white py-2 px-4 rounded-md">
            Login
          </button>
        </div>
      </nav>
    </div>
  );
}
